// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzXDk_6H7RCWwPBilCKMN8XN1-MKdIc20',
    appId: '1:258594689815:web:6ce3dfc93c5f55179c9d52',
    messagingSenderId: '258594689815',
    projectId: 'steplive-454ac',
    authDomain: 'steplive-454ac.firebaseapp.com',
    storageBucket: 'steplive-454ac.firebasestorage.app',
    measurementId: 'G-59Q4216HGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZPGdMCDyH6hG0mWKsigd7kvS9H_vQaYI',
    appId: '1:258594689815:android:0a80f72e8da4cf3f9c9d52',
    messagingSenderId: '258594689815',
    projectId: 'steplive-454ac',
    storageBucket: 'steplive-454ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTstPhtdg35jGMIuX2Y2gv2yv5Xs38dnk',
    appId: '1:258594689815:ios:3b41ee87fb08ce309c9d52',
    messagingSenderId: '258594689815',
    projectId: 'steplive-454ac',
    storageBucket: 'steplive-454ac.firebasestorage.app',
    androidClientId: '258594689815-86k4m642jruf9tbtdcfheabp5f310bhr.apps.googleusercontent.com',
    iosClientId: '258594689815-vjvt8h8l55qaps2j5chvliv4qv27hsnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarckfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTstPhtdg35jGMIuX2Y2gv2yv5Xs38dnk',
    appId: '1:258594689815:ios:3b41ee87fb08ce309c9d52',
    messagingSenderId: '258594689815',
    projectId: 'steplive-454ac',
    storageBucket: 'steplive-454ac.firebasestorage.app',
    androidClientId: '258594689815-86k4m642jruf9tbtdcfheabp5f310bhr.apps.googleusercontent.com',
    iosClientId: '258594689815-vjvt8h8l55qaps2j5chvliv4qv27hsnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tarckfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzXDk_6H7RCWwPBilCKMN8XN1-MKdIc20',
    appId: '1:258594689815:web:4f7a6c17e89bc1929c9d52',
    messagingSenderId: '258594689815',
    projectId: 'steplive-454ac',
    authDomain: 'steplive-454ac.firebaseapp.com',
    storageBucket: 'steplive-454ac.firebasestorage.app',
    measurementId: 'G-73F3SX8D5V',
  );

}